version: '3.4'

services:
  webapi_func:
    image: webapi_func
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=54.152.77.50;Port=5432;Database=postgres;Username=postgres;Password=postgres
