version: "3.9"

services:
  webapi_func:
    image: webapi_func
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webapi_func
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - DB_HOST=webrds.cengsmwc6d3c.us-east-1.rds.amazonaws.com
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=33557788
      - DB_PORT=15432
    networks:
      - webapi_network
    restart: on-failure

networks:
  webapi_network:
    driver: bridge
